import { createI18n } from 'vue-i18n'
import { ref } from 'vue'

export const locale = ref<'zh-CN' | 'en'>((localStorage.getItem('frp-panel.locale') as 'zh-CN'|'en') || 'zh-CN')

export const availableLocales = [
  { code: 'zh-CN', name: '中文', flag: '🇨🇳' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
] as const

const rawMessages = {
  'zh-CN': {
    brand: { name:'frp-panel', product:'FRP PANEL', description:'安全隧道控制平面' },
    nav: { master:'Master 控制台', masterHint:'控制平面', overview:'概览', clients:'Clients', servers:'Servers', tunnels:'Tunnels', openMenu:'打开菜单' },
    theme: { title:'主题', system:'跟随系统', systemHint:'使用系统外观设置', light:'浅色', lightHint:'白色背景与深色文字', dark:'深色', darkHint:'黑色背景与浅色文字' },
    auth: { signIn:'登录 Master', signInHint:'使用账户访问控制平面', register:'创建 Owner 账户', registerHint:'首次部署时创建唯一 Owner', username:'用户名', email:'邮箱', password:'密码', currentPassword:'当前密码', newPassword:'新密码', confirmPassword:'确认密码', submit:'继续', create:'创建账户', logout:'退出登录', switchRegister:'还没有账户？创建 Owner', switchLogin:'返回登录', loading:'处理中…' },
    account: { title:'账户设置', profile:'个人资料', password:'修改密码', save:'保存密码', role:'角色', passwordHint:'密码至少 12 个字符，修改后需要重新登录' },
    common: { create:'创建', edit:'编辑', delete:'删除', cancel:'取消', confirm:'确认', close:'关闭', refresh:'刷新', copy:'复制', copied:'已复制', search:'搜索', selectOption:'请选择', all:'全部', autoRefresh:'每 5 秒自动更新', enabled:'已启用', disabled:'已停用', configured:'已配置', unconfigured:'未配置', pending:'待配置', online:'在线', offline:'离线', error:'异常', install:'安装命令', rotate:'轮换凭据', noData:'暂无数据', save:'保存', previous:'上一页', next:'下一页', loading:'加载中…', success:'操作成功' },
    updates: { version:'版本', masterVersion:'Master 版本', current:'当前', latest:'最新', newVersion:'有新版本', updateNow:'立即更新', updateMasterTitle:'更新 Master', masterDowntime:'Master 将短暂重启；现有数据与隧道配置保留。失败时自动回退。', imageBootstrap:'请先拉取并重新部署一次新镜像，之后才能在网页中更新。', checkFailed:'检查失败', upToDate:'已是最新版本', releaseNotes:'查看发布说明', auto:'自动更新', policy:'更新设置', policyHint:'仅 Server 使用自动更新；在维护窗口内每日最多尝试一次，更新时隧道可能短暂中断。', autoHint:'关闭后可从版本号旁手动更新。', timeZone:'时区（IANA）', windowStart:'窗口开始', windowEnd:'窗口结束', serverTitle:'更新 Server', serverDowntime:'此 Server 将短暂重启，隧道可能中断。失败时自动回退。确认继续？', started:'更新请求已发送，请在列表查看进度', clientTitle:'Client 升级命令', clientLocalOnly:'请在目标 Client 主机本地执行此命令；管理平台不会远程安装或重启 Client。', clientTarget:'目标 Client', clientVerify:'升级后请等待版本自动刷新，并确认 Agent 在线。', states:{ queued:'排队中', downloading:'下载中', staged:'已校验，等待重启', restarting:'重启中', verifying:'验证中', succeeded:'更新成功', failed:'更新失败', rolled_back:'已回退' } },
    clients: { title:'Clients', description:'物理业务主机及其 Client Agent', create:'添加 Client', id:'Client ID', comment:'备注', state:'配置状态', status:'运行状态', allConfiguration:'全部配置状态', allStatus:'全部运行状态', tunnels:'Tunnels', empty:'还没有 Client', emptyHint:'创建 Client 后复制安装命令到目标主机', createTitle:'添加 Client', editTitle:'编辑 Client', installTitle:'安装 Client Agent', platform:'目标系统', rotateTitle:'轮换 Client 凭据', deleteTitle:'删除 Client', deleteHint:'删除前请先删除依赖 Tunnel。', rotateHint:'轮换会使当前 Agent 凭据失效，需要重新安装。', acknowledge:'我了解轮换会中断当前连接', enabledHint:'关闭后将停止该 Client 的 Tunnel 连接。', commandHint:'仅在目标 Client 上执行一次；命令不会把文件安装到当前目录。', locationIp:'定位 IP（可选）', locationIpPlaceholder:'留空自动探测', locationIpHint:'Clash/TUN 等代理导致自动定位错误时，填写本机真实公网 IP；清空后恢复自动定位。' },
    servers: { title:'Servers', description:'FRPS 数据平面，可配置多个', create:'添加 Server', id:'Server ID', address:'公网地址', bindPort:'Bind port', serverPort:'Server port', portHint:'Bind port 和 Server port 必须不同，也不能与该 Server 的 Tunnel 远端端口冲突；部署前请确认两个端口在目标 Server 主机上未被其他程序占用。修改后需重新应用 Compose。', portConflict:'Bind port 和 Server port 不能相同。', comment:'备注', state:'配置状态', status:'运行状态', allConfiguration:'全部配置状态', allStatus:'全部运行状态', tunnels:'Tunnels', empty:'还没有 Server', emptyHint:'创建 Server 后部署 FRPS 容器', createTitle:'添加 Server', editTitle:'编辑 Server', deployTitle:'部署 Server', rotateTitle:'轮换 Server 凭据', deleteTitle:'删除 Server', deleteHint:'删除前请先删除依赖 Tunnel。', commandHint:'FRPS 默认由 Docker Compose 管理；Master URL 只配置一次。' },
    tunnels: { title:'Tunnels', description:'每条 Tunnel 选择一个 Client 和一个 Server', create:'创建 Tunnel', editTitle:'编辑 Tunnel', name:'名称', client:'Client', server:'Server', type:'类型', localHost:'本地地址', localPort:'本地端口', remotePort:'远端端口', remoteConnection:'远程连接', connection:'本地连接', status:'状态', allStatus:'全部状态', enabledHint:'关闭后会停止该转发规则，但保留当前配置。', empty:'还没有 Tunnel', emptyHint:'先准备 Client 和 Server，再创建转发。', deleteTitle:'删除 Tunnel', deleteWarning:'删除后该 Tunnel 的转发会立即停止，且无法恢复。', deleteMessage:'待删除 Tunnel：' },
    overview: { title:'概览', description:'Master、Server、Client 与 Tunnel 的统一视图', clients:'Clients', servers:'Servers', tunnels:'Tunnels', next:'建议流程', nextHint:'创建 Server → 创建 Client → 在 Tunnel 中选择两端 → 部署 Agent/FRPS', topologyTitle:'网络拓扑', topologyEmpty:'暂无节点，先添加 Server 和 Client', mapLoading:'正在加载地图与端点位置…', mapNoLocation:'暂无可用公网 IP，端点上线后将自动定位', mapLocated:'已定位', mapUnlocated:'未定位', mapConnections:'连接关系', mapMaster:'Master 控制平面', mapClient:'Client', mapServer:'Server', mapPrivate:'私有或未公开 IP', mapGeoError:'地理位置服务暂时不可用', mapLastSeen:'最后连接', mapFit:'定位全部端点', mapObservedIp:'连接 IP', mapDataSource:'地图优先使用手工定位及 Agent 直连探测 IP；仅有连接 IP 时可能显示代理出口。', locationSources:{manual:'手工定位',agent_probe:'Agent 直连探测',observed:'连接 IP，可能是代理出口',configured:'Server 配置地址'} },
    problems: { dependencies:'存在依赖 Tunnel', immutable:'ID 不可修改', required:'请填写必填项' }
  },
  en: {
    brand: { name:'frp-panel', product:'FRP PANEL', description:'Secure tunnel control plane' },
    nav: { master:'Master console', masterHint:'Control plane', overview:'Overview', clients:'Clients', servers:'Servers', tunnels:'Tunnels', openMenu:'Open menu' },
    theme: { title:'Theme', system:'System', systemHint:'Follow your system preference', light:'Light', lightHint:'White surfaces and dark text', dark:'Dark', darkHint:'Dark surfaces and light text' },
    auth: { signIn:'Sign in to Master', signInHint:'Use your account to access the control plane', register:'Create Owner account', registerHint:'Create the only Owner during first setup', username:'Username', email:'Email', password:'Password', currentPassword:'Current password', newPassword:'New password', confirmPassword:'Confirm password', submit:'Continue', create:'Create account', logout:'Sign out', switchRegister:'Need an account? Create Owner', switchLogin:'Back to sign in', loading:'Working…' },
    account: { title:'Account settings', profile:'Profile', password:'Change password', save:'Save password', role:'Role', passwordHint:'Use at least 12 characters. You will sign in again after changing it.' },
    common: { create:'Create', edit:'Edit', delete:'Delete', cancel:'Cancel', confirm:'Confirm', close:'Close', refresh:'Refresh', copy:'Copy', copied:'Copied', search:'Search', selectOption:'Select an option', all:'All', autoRefresh:'Auto-refreshes every 5 seconds', enabled:'Enabled', disabled:'Disabled', configured:'Configured', unconfigured:'Unconfigured', pending:'Pending', online:'Online', offline:'Offline', error:'Error', install:'Install command', rotate:'Rotate credentials', noData:'No data', save:'Save', previous:'Previous', next:'Next', loading:'Loading…', success:'Done' },
    updates: { version:'Version', masterVersion:'Master version', current:'Current', latest:'Latest', newVersion:'New version', updateNow:'Update now', updateMasterTitle:'Update Master', masterDowntime:'Master will restart briefly. Data and tunnel settings are retained; a failed startup is rolled back.', imageBootstrap:'Pull and redeploy the new image once before updating in the console.', checkFailed:'Check failed', upToDate:'Up to date', releaseNotes:'Release notes', auto:'Auto-update', policy:'Update settings', policyHint:'Only Servers update automatically. One attempt per day within the maintenance window; tunnels may briefly disconnect.', autoHint:'When off, update manually from the version column.', timeZone:'Time zone (IANA)', windowStart:'Window start', windowEnd:'Window end', serverTitle:'Update Server', serverDowntime:'This Server will restart briefly and tunnels may disconnect. Failed startup is rolled back. Continue?', started:'Update requested; follow progress in the list', clientTitle:'Client update command', clientLocalOnly:'Run this command locally on the target Client. The console does not remotely install or restart Clients.', clientTarget:'Target Client', clientVerify:'Wait for the version to refresh and confirm the Agent is online.', states:{ queued:'Queued', downloading:'Downloading', staged:'Verified; awaiting restart', restarting:'Restarting', verifying:'Verifying', succeeded:'Updated', failed:'Failed', rolled_back:'Rolled back' } },
    clients: { title:'Clients', description:'Physical business hosts running a Client Agent', create:'Add Client', id:'Client ID', comment:'Comment', state:'Configuration', status:'Runtime status', allConfiguration:'All configuration states', allStatus:'All runtime states', tunnels:'Tunnels', empty:'No Clients yet', emptyHint:'Create a Client and copy its install command to the host', createTitle:'Add Client', editTitle:'Edit Client', installTitle:'Install Client Agent', platform:'Target OS', rotateTitle:'Rotate Client credentials', deleteTitle:'Delete Client', deleteHint:'Delete dependent Tunnels first.', rotateHint:'Rotation invalidates the current Agent credential and requires reinstall.', acknowledge:'I understand this will interrupt the current connection', enabledHint:'Disabling stops this Client’s Tunnel connections.', commandHint:'Run once on the target Client; files are installed in the native system location.', locationIp:'Location IP (optional)', locationIpPlaceholder:'Leave blank for automatic detection', locationIpHint:'Set the host’s real public IP if Clash/TUN changes its apparent location. Clear to restore automatic detection.' },
    servers: { title:'Servers', description:'FRPS data-plane hosts; add as many as you need', create:'Add Server', id:'Server ID', address:'Public address', bindPort:'Bind port', serverPort:'Server port', portHint:'Bind port and Server port must be different and must not conflict with Tunnel remote ports on this Server. Before deployment, confirm both ports are free on the target Server host. Re-apply Compose after changing this value.', portConflict:'Bind port and Server port must be different.', comment:'Comment', state:'Configuration', status:'Runtime status', allConfiguration:'All configuration states', allStatus:'All runtime states', tunnels:'Tunnels', empty:'No Servers yet', emptyHint:'Create a Server and deploy its FRPS container', createTitle:'Add Server', editTitle:'Edit Server', deployTitle:'Deploy Server', rotateTitle:'Rotate Server credentials', deleteTitle:'Delete Server', deleteHint:'Delete dependent Tunnels first.', commandHint:'FRPS is managed by Docker Compose; configure the Master URL once.' },
    tunnels: { title:'Tunnels', description:'Each Tunnel selects one Client and one Server', create:'Create Tunnel', editTitle:'Edit Tunnel', name:'Name', client:'Client', server:'Server', type:'Type', localHost:'Local host', localPort:'Local port', remotePort:'Remote port', remoteConnection:'Remote connection', connection:'Local connection', status:'Runtime status', allStatus:'All statuses', enabledHint:'Disabling stops this forwarding rule while keeping its configuration.', empty:'No Tunnels yet', emptyHint:'Prepare a Client and Server, then create a forwarding rule.', deleteTitle:'Delete Tunnel', deleteWarning:'Deleting this Tunnel stops forwarding immediately and cannot be undone.', deleteMessage:'Tunnel to delete:' },
    overview: { title:'Overview', description:'A unified view of Master, Servers, Clients and Tunnels', clients:'Clients', servers:'Servers', tunnels:'Tunnels', next:'Suggested flow', nextHint:'Create Server → create Client → select both in a Tunnel → deploy Agent/FRPS', topologyTitle:'Network topology', topologyEmpty:'No nodes yet — add a Server and Client to see them here', mapLoading:'Loading the map and endpoint locations…', mapNoLocation:'No public IP is available yet; endpoints are located after they connect', mapLocated:'Located', mapUnlocated:'Unlocated', mapConnections:'Connections', mapMaster:'Master control plane', mapClient:'Client', mapServer:'Server', mapPrivate:'Private or undisclosed IP', mapGeoError:'The geolocation service is temporarily unavailable', mapLastSeen:'Last connection', mapFit:'Fit all endpoints', mapObservedIp:'Connection IP', mapDataSource:'The map prefers manual and Agent direct probe IPs. Connection IPs may be proxy exits.', locationSources:{manual:'Manual location',agent_probe:'Agent direct probe',observed:'Connection IP, possibly a proxy exit',configured:'Configured Server address'} },
    problems: { dependencies:'Dependent Tunnels exist', immutable:'IDs cannot be changed', required:'Complete the required fields' }
  }
}

/**
 * Keep messages as static functions so the runtime-only vue-i18n build never
 * needs to compile strings with `new Function`. This is required by the
 * console's strict Content-Security-Policy (`unsafe-eval` is intentionally
 * disabled).
 */
const toStaticMessages = (value: unknown): unknown => {
  if (typeof value === 'string') return () => value
  if (Array.isArray(value)) return value.map(toStaticMessages)
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, toStaticMessages(child)]))
  }
  return value
}

export const messages = toStaticMessages(rawMessages)

export const i18n = createI18n({ legacy:false, locale:locale.value, fallbackLocale:'en', messages: messages as any })
export function setLocale(next: string) { const value = next === 'en' ? 'en' : 'zh-CN'; locale.value = value; (i18n.global.locale as { value: string }).value = value; localStorage.setItem('frp-panel.locale', value); document.documentElement.lang = value }
